[package]
name = "phonon"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_deref = "1"
glam = "0.25"
biquad = "0.4"
rand = "0.8"
ndarray = "0.15.6"
num = "0.4.1"
rustfft = "6.2.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "audio_buffer_bench"
harness = false
