[package]
name = "phonon"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_deref = "1"
glam = "0.25"
biquad = "0.4"
rand = "0.8"
ndarray = "0.15"

[dev-dependencies]
kira = "0.8"
criterion = { version = "0.5", features = ["html_reports"] }
plotters = "0.3"

[[bench]]
name = "audio_buffer_bench"
harness = false