[package]
name = "phonon"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Unofficial Steam Audio Rust rewrite"
repository = "https://github.com/GitGhillie/phonon_rs"

[dependencies]
derive_deref = "1"
glam = "0.25"
biquad = "0.4"
rand = "0.8"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
plotters = "0.3"

[[bench]]
name = "audio_buffer_bench"
harness = false